# Generated by Django 4.2.6 on 2024-01-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_product',
            name='image',
            field=models.ImageField(upload_to='product/media/images/'),
        ),
    ]
