# Generated by Django 4.2.6 on 2024-01-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_feature_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_arrevals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=60)),
                ('cortoon_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('last_updated', models.TimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product/media/images/')),
            ],
        ),
    ]
